image:
  - Visual Studio 2017

clone_folder: c:\projects\source

environment:
  matrix:
  - GENERATOR: MinGW Makefiles
  - GENERATOR: Visual Studio 15 2017 Win64

install:
  # See https://docs.conan.io/en/latest/integrations/appveyor.html
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install ..
  - cmd: cmake -DCMAKE_BUILD_TYPE=Debug -G "%GENERATOR%" ..
  - cmd: cmake --build . --config "Debug"

test_script:
  - cmd: ctest -C Debug
